spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka-client
      password: 526982649a256cd93ca8d22cc394d5b1660254d4e2fb0982a71986e8b0e0374c
      roles: USER

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
  server:
    eviction-interval-timer-in-ms: 50000
    wait-time-in-ms-when-sync-empty: 5