server:
  port: 9000

spring:
  application:
    name: zuul-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka%2Dclient:526982649a256cd93ca8d22cc394d5b1660254d4e2fb0982a71986e8b0e0374c@localhost:8761/eureka}
  instance:
    preferIpAddress: false

zuul:
  routes:
    auth-service:
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
      path: /auth/**
      service-id: security-service
    atype-catealog:
      path: /products/**
      service-id: gallery-service
