server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    register-with-eureka: true
  instance:
    appname: searcher-service

spring:
  application:
    name: searcher-service

ribbon:
  restclient:
    enabled: true
