server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: searcher

spring:
  application:
    name: searcher-service
ribbon:
  restclient:
    enabled: true
